# Generated by Django 3.1.1 on 2021-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
