# Generated by Django 3.1.1 on 2021-01-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_doctor_isapproved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scans',
            new_name='Scan',
        ),
    ]
