# Generated by Django 3.1.1 on 2021-01-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20210112_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
