# Generated by Django 3.1.1 on 2021-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20210112_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='isReported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scan',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
