# Generated by Django 3.1.1 on 2021-01-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20210115_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
